service: testingTasks

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::*'

functions:
  printBuckets:
    handler: handler.printBuckets
    events: 
      - schedule: rate(1 minute)
